WebStore/WebStore/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Infrastructure.Interfaces;
using WebStore.ViewModels;
using WebStore.Domain.Entities;
using WebStore.Infrastructure.Map;

namespace WebStore.Components
{
	public class BrandsViewComponent : ViewComponent
	{
		private readonly IProductData _ProductData;

		public BrandsViewComponent(IProductData ProductData)
		{
			_ProductData = ProductData;
		}

		public IViewComponentResult Invoke()
		{
			var brands = GetBrands();
			return View(brands);
		}

		private IEnumerable<BrandViewModel> GetBrands()
		{
			return _ProductData.GetBrands().Select(c => c.CreateViewModel());
		}
	}
}

WebStore/WebStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.Infrastructure.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
	public class CartController : Controller
	{
		private readonly ICartService _CartService;
		private readonly IOrdersService _OrdersService;

		public CartController(ICartService CartService, IOrdersService OrdersService)
		{
			_CartService = CartService;
			_OrdersService = OrdersService;
		}

		public IActionResult Details()
		{
			var model = new DetailsViewModel()
			{
				CartViewModel = _CartService.TransformCart(),
				OrderViewModel = new OrderViewModel()
			};

			return View(model);
		}

		public IActionResult DecrementFromCart(int id)
		{
			_CartService.DecrementFromCart(id);
			return RedirectToAction("Details");
		}

		public IActionResult RemoveFromCart(int id)
		{
			_CartService.RemoveFromCart(id);
			return RedirectToAction("Details");
		}

		public IActionResult RemoveAll()
		{
			_CartService.RemoveAll();
			return RedirectToAction("Details");
		}

		public IActionResult AddToCart(int id) //, string returnUrl)
		{
			_CartService.AddToCart(id);
			return RedirectToAction("Details");
			//return Redirect(returnUrl);
		}

		[HttpPost]
		[AutoValidateAntiforgeryToken]
		public IActionResult CheckOut(OrderViewModel model)
		{
			if (!ModelState.IsValid)
				return View(nameof(Details), new DetailsViewModel()
				{
					CartViewModel = _CartService.TransformCart(),
					OrderViewModel = model
				});

			var order = _OrdersService.CreateOrder(model, _CartService.TransformCart(), User.Identity.Name);

			_CartService.RemoveAll();

			return RedirectToAction("OrderConfirmed", new { Id = order.Id });
		}

		public IActionResult OrderConfirmed(int id)
		{
			ViewBag.OrderId = id;
			return View();
		}
	}
}

WebStore/WebStore/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities;
using WebStore.Infrastructure.Interfaces;
using WebStore.Infrastructure.Map;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
	public class CatalogController : Controller
	{
		private readonly IProductData _ProductData;

		public CatalogController(IProductData ProductData)
		{
			_ProductData = ProductData;
		}

		public IActionResult Shop(int? SectionId, int? BrandId)
		{
			var products = _ProductData.GetProducts(new ProductFilter() { SectionId = SectionId, BrandId = BrandId });

			var catalog_models = new CatalogViewModel()
			{
				SectionId = SectionId,
				BrandId = BrandId,
				Products = products.Select(c => c.CreateViewModel())
			};

			return View(catalog_models);
		}

		public IActionResult ProductDetails(int id)
		{
			var product = _ProductData.GetProductById(id);
			if (product is null)
				return NotFound();

			return View(new ProductViewModel()
			{
				Id = product.Id,
				Name = product.Name,
				Price = product.Price,
				Order = product.Order,
				ImageUrl = product.ImageUrl,
				Brand = product.Brand?.Name
			});
		}
	}
}

WebStore/WebStore/Controllers/EmployesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Infrastructure.Implementations;
using WebStore.Infrastructure.Interfaces;
using WebStore.Models;

namespace WebStore.Controllers
{
	//[Route("Users/[Action]")]
	[Authorize]
	public class EmployesController : Controller
	{
		private readonly IEmployeesData _EmployeesData;

		public EmployesController(IEmployeesData EmployeesData)
		{
			_EmployeesData = EmployeesData;
		}

		public IActionResult Index()
		{
			return View(_EmployeesData.GetAll());
		}

		//[Route("Info/{id}")]
		public IActionResult Details(int id)
		{
			var employee = _EmployeesData.GetById(id);
			if (employee == null)
				return NotFound();

			return View("EmployeeView", employee);
		}

		[Authorize(Roles = Domain.Entities.User.RoleAdmin)]
		public ActionResult Edit(int? id)
		{
			Employee employee;
			if (id != null)
			{
				employee = _EmployeesData.GetById(id.Value);
				if (employee is null)
					return NotFound();
			}
			else
			{
				employee = new Employee();
			}
			return View(employee);
		}

		[HttpPost]
		[Authorize(Roles = Domain.Entities.User.RoleAdmin)]
		public ActionResult Edit(Employee employee, [FromServices] IMapper mapper)
		{
			if (employee.Age < 18)
				ModelState.AddModelError("Age", "Возраст слишком маленький");

			if (employee.Age > 120)
				ModelState.AddModelError("Age", "Возраст слишком большой");

			//if (employee.Age % 2 == 0)
			//	ModelState.AddModelError("Age", "Четный возраст");

			if (!ModelState.IsValid) return View(employee);

			if (employee.Id > 0)
			{
				Employee dbEmployee = _EmployeesData.GetById(employee.Id);
				if (dbEmployee is null)
					return NotFound();

				//dbEmployee.SurName = employee.SurName;
				//dbEmployee.FirstName = employee.FirstName;
				//dbEmployee.Patronymic = employee.Patronymic;
				//dbEmployee.Age = employee.Age;

				//AutoMapper.Mapper.Map(employee, dbEmployee);

				mapper.Map(employee, dbEmployee);
			}
			else
			{
				_EmployeesData.AddNew(employee);
			}

			_EmployeesData.SaveChanges();

			return RedirectToAction("Index");
		}
		
		[Authorize(Roles = Domain.Entities.User.RoleAdmin)]
		public ActionResult Delete(int id)
		{
			Employee dbEmployee = _EmployeesData.GetById(id);
			if (dbEmployee is null)
				return NotFound();
			_EmployeesData.Delete(id);
			return RedirectToAction("Index");
		}
	}
}

WebStore/WebStore/Views/Shared/Partial/_FeaturesItems.cshtml
@model IEnumerable<WebStore.ViewModels.ProductViewModel>
<div class="features_items">
	<!--features_items-->
	<h2 class="title text-center">Features Items</h2>

	@foreach (var product in Model)
	{
		<div class="col-sm-4">
			<div class="product-image-wrapper">
				<div class="single-products">
					<div class="productinfo text-center">
						<img src="~/@product.ImageUrl" alt="" />
						<h2>@product.Price.ToString("C")</h2>
						<p><a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id">@product.Name</a></p>
						<a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@product.Id" class="btn btn-default add-to-cart">
							<i class="fa fa-shopping-cart"></i>Add to cart
						</a>
					</div>
					<div class="product-overlay">
						<div class="overlay-content">
							<h2>@product.Price.ToString("C")</h2>
							<p><a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id">@product.Name</a></p>
							<a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@product.Id" class="btn btn-default add-to-cart">
								<i class="fa fa-shopping-cart"></i>Add to cart
							</a>
						</div>
					</div>
				</div>
				<div class="choose">
					<ul class="nav nav-pills nav-justified">
						<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
						<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
					</ul>
				</div>
			</div>
		</div>
	}
</div><!--features_items-->

WebStore/WebStore/Views/Shared/Partial/_Footer.cshtml
<footer id="footer">
	<!--Footer-->
	<div class="footer-top">
		<div class="container">
			<div class="row">
				<div class="col-sm-2">
					<div class="companyinfo">
						<h2><span>e</span>-shopper</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
					</div>
				</div>
				<div class="col-sm-7">
					<div class="col-sm-3">
						<div class="video-gallery text-center">
							<a href="#">
								<div class="iframe-img">
									<img src="~/images/home/iframe1.png" alt="" />
								</div>
								<div class="overlay-icon">
									<i class="fa fa-play-circle-o"></i>
								</div>
							</a>
							<p>Circle of Hands</p>
							<h2>24 DEC 2014</h2>
						</div>
					</div>

					<div class="col-sm-3">
						<div class="video-gallery text-center">
							<a href="#">
								<div class="iframe-img">
									<img src="~/images/home/iframe2.png" alt="" />
								</div>
								<div class="overlay-icon">
									<i class="fa fa-play-circle-o"></i>
								</div>
							</a>
							<p>Circle of Hands</p>
							<h2>24 DEC 2014</h2>
						</div>
					</div>

					<div class="col-sm-3">
						<div class="video-gallery text-center">
							<a href="#">
								<div class="iframe-img">
									<img src="~/images/home/iframe3.png" alt="" />
								</div>
								<div class="overlay-icon">
									<i class="fa fa-play-circle-o"></i>
								</div>
							</a>
							<p>Circle of Hands</p>
							<h2>24 DEC 2014</h2>
						</div>
					</div>

					<div class="col-sm-3">
						<div class="video-gallery text-center">
							<a href="#">
								<div class="iframe-img">
									<img src="~/images/home/iframe4.png" alt="" />
								</div>
								<div class="overlay-icon">
									<i class="fa fa-play-circle-o"></i>
								</div>
							</a>
							<p>Circle of Hands</p>
							<h2>24 DEC 2014</h2>
						</div>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="address">
						<img src="~/images/home/map.png" alt="" />
						<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer-widget">
		<div class="container">
			<div class="row">
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>Service</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Online Help</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Order Status</a></li>
							<li><a href="#">Change Location</a></li>
							<li><a href="#">FAQ’s</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>Quock Shop</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">T-Shirt</a></li>
							<li><a href="#">Mens</a></li>
							<li><a href="#">Womens</a></li>
							<li><a href="#">Gift Cards</a></li>
							<li><a href="#">Shoes</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>Policies</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Terms of Use</a></li>
							<li><a href="#">Privecy Policy</a></li>
							<li><a href="#">Refund Policy</a></li>
							<li><a href="#">Billing System</a></li>
							<li><a href="#">Ticket System</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>About Shopper</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Company Information</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Store Location</a></li>
							<li><a href="#">Affillate Program</a></li>
							<li><a href="#">Copyright</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-3 col-sm-offset-1">
					<div class="single-widget">
						<h2>About Shopper</h2>
						<form action="#" class="searchform">
							<input type="text" placeholder="Your email address" />
							<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
							<p>Get the most recent updates from <br />our site and be updated your self...</p>
						</form>
					</div>
				</div>

			</div>
		</div>
	</div>

	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
				<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
			</div>
		</div>
	</div>

</footer><!--/Footer-->

WebStore/WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
	<!--header-->
	<div class="header_top">
		<!--header_top-->
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<div class="contactinfo">
						<ul class="nav nav-pills">
							<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
							<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="social-icons pull-right">
						<ul class="nav navbar-nav">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div><!--/header_top-->

	<div class="header-middle">
		<!--header-middle-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<div class="logo pull-left">
						<a asp-controller="Home" asp-action="Index"><img src="~/images/home/logo.png" alt="" /></a>
					</div>
					<div class="btn-group pull-right">
						<div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
								USA
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li><a href="#">Canada</a></li>
								<li><a href="#">UK</a></li>
							</ul>
						</div>

						<div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
								DOLLAR
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li><a href="#">Canadian Dollar</a></li>
								<li><a href="#">Pound</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-sm-8">
					@*@await Component.InvokeAsync("UserInfo");*@
					<vc:user-info/>
				</div>
			</div>
		</div>
	</div><!--/header-middle-->

	<div class="header-bottom">
		<!--header-bottom-->
		<div class="container">
			<div class="row">
				<div class="col-sm-9">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>
					<div class="mainmenu pull-left">
						<ul class="nav navbar-nav collapse navbar-collapse">
							<li><a asp-controller="Home" asp-action="Index" class="active">Home</a></li>
							<li class="dropdown">
								<a href="#">Shop<i class="fa fa-angle-down"></i></a>
								<ul role="menu" class="sub-menu">
									<li><a asp-controller="Catalog" asp-action="Shop">Products</a></li>
									<li><a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="1">Product Details</a></li>
									<li><a asp-controller="Home" asp-action="Checkout">Checkout</a></li>
									<li><a asp-controller="Cart" asp-action="Details">Корзина</a></li>
									<li><a asp-controller="Account" asp-action="Login">Login</a></li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#">Blog<i class="fa fa-angle-down"></i></a>
								<ul role="menu" class="sub-menu">
									<li><a asp-controller="Home" asp-action="Blog">Blog List</a></li>
									<li><a asp-controller="Home" asp-action="BlogSingle">Blog Single</a></li>
								</ul>
							</li>
							<li><a asp-controller="Home" asp-action="Error404">404</a></li>
							<li><a asp-controller="Home" asp-action="ContactUs">Contact</a></li>
							<li><a asp-controller="Employes" asp-action="Index">Сотрудники</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="search_box pull-right">
						<input type="text" placeholder="Search" />
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

WebStore/WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
<div class="left-sidebar">
	@await Component.InvokeAsync("Sections")

	@await Component.InvokeAsync("Brands")


	<div class="price-range">
		<!--price-range-->
		<h2>Price Range</h2>
		<div class="well text-center">
			<input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
			<b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
		</div>
	</div><!--/price-range-->

	<div class="shipping text-center">
		<!--shipping-->
		<img src="~/images/home/shipping.jpg" alt="" />
	</div><!--/shipping-->

</div>